INSERT INTO sports (name, description) VALUES ('Ping Pong', 'Deporte de raqueta con una pequeña pelota.'),
('Spikeball', 'Juego competitivo con pelota y red circular.'),
('Volleyball', 'Juego de equipo con balón y red alta.'),
('Slackline', 'Equilibrio sobre una cinta tensa entre dos puntos.'),
('Parkour', 'Desplazarse superando obstáculos urbanos de manera fluida y eficiente.'),
('Ultimate Frisbee', 'Juego de equipo con un disco volador en parques o playas.'),
('Slackline', 'Equilibrio sobre una cinta tensa entre dos puntos, común en parques.'),
('Street Workout', 'Ejercicios de calistenia en parques usando barras y mobiliario urbano.'),
('Running', 'Carrera continua en rutas urbanas, parques o a lo largo de la costa.'),
('Ciclismo Urbano', 'Desplazarse en bicicleta por la ciudad, tanto como deporte como medio de transporte.'),
('Skateboarding', 'Deslizamiento sobre tabla en plazas, parques y skateparks.'),
('Longboard', 'Variante del skate, ideal para descensos y largas distancias.'),
('Rollerblading', 'Patinaje en línea en parques, paseos marítimos o calles anchas.'),
('Yoga', 'Práctica de yoga en parques, playas o espacios abiertos.'),
('Fútbol playa', 'Partido de fútbol en la arena de la playa.'),
('Fútbol Sala', 'Fútbol en canchas exteriores de cemento o césped artificial.'),
('Baloncesto', 'Partidos de baloncesto en canchas urbanas abiertas.'),
('Petanca', 'Juego de precisión lanzando bolas metálicas en parques.'),
('Badminton', 'Juego de raqueta con volante, se puede jugar en parques y playas.'),
('Voleibol de playa', 'Voleibol jugado en la arena, común en las playas.'),
('Voleibol en césped', 'Variante jugada en parques, sobre césped natural.'),
('Ping Pong portátil', 'Mesas plegables o redes portátiles en plazas o parques.'),
('Frisbee Golf', 'Lanzar frisbee para alcanzar objetivos en parques (similar al golf).'),
('Carreras de orientación', 'Navegación con mapa en áreas urbanas o parques grandes.'),
('Entrenamiento funcional', 'Ejercicios de alta intensidad al aire libre utilizando el propio peso corporal.'),
('Boxeo sombra', 'Entrenamiento de boxeo sin contacto, en parques o espacios abiertos.'),
('Patinaje en quad', 'Patinaje sobre ruedas cuadradas, diferente del inline.'),
('Acrobacias en telas', 'Ejercicio aéreo usando cintas colgadas de árboles en parques.'),
('Crossfit', 'Ejercicios funcionales en grupo, utilizando espacios públicos.'),
('Capoeira', 'Arte marcial brasileño, mezcla de lucha, danza y acrobacias.'),
('Plogging', 'Correr mientras recoges basura para limpiar el entorno urbano.'),
('Senderismo urbano', 'Caminatas exploratorias por la ciudad, parques y áreas naturales.'),
('Rugby Touch', 'Variante del rugby sin contacto, jugado en césped o arena.'),
('Freestyle Football', 'Habilidades y trucos con el balón en plazas o parques.'),
('Kitesurf en la playa', 'Utilizar el viento para surfear con una cometa en playas con condiciones adecuadas.'),
('Bodyweight Training', 'Entrenamientos de fuerza usando solo el peso corporal en espacios públicos.'),
('Trekking Urbano', 'Caminatas por rutas largas que atraviesan áreas urbanas y parques.'),
('Aikido al aire libre', 'Practicar movimientos de Aikido en un espacio abierto.'),
('Boxeo al aire libre', 'Entrenamientos de boxeo en parques, usando equipamiento portátil.'),
('Climbing Urbano (buildering)', 'Escalar estructuras urbanas (practicado por expertos).'),
('Fotografía deportiva', 'Recorrer la ciudad capturando imágenes de deportes en acción.'),
('Petanca de Playa', 'Variante de la petanca jugada en la arena.'),
('Patinaje de velocidad', 'Competir o entrenar en patines en línea en áreas amplias y lisas.'),
('Paddle Surf', 'Remar de pie sobre una tabla de surf en aguas tranquilas (playas o lagos).'),
('Acrobacias en cuerda floja', 'Variante del slackline pero con cuerdas más altas y tensas.'),
('Tiro con arco portátil', 'Práctica de tiro en espacios públicos, usando equipo portátil y seguro.'),
('Fútbol Americano Flag', 'Variante del fútbol americano donde se quitan banderas en lugar de hacer placajes.'),
('Zumba al aire libre', 'Sesiones de Zumba en espacios abiertos, como playas o parques.'),
('Pádel Playa', 'Jugar pádel en la arena con una red portátil.'),
('Danza urbana (Hip-Hop, Breakdance)', 'Bailes urbanos en plazas o parques.'),
('Bouldering al aire libre', 'Escalada en bloques de roca naturales o artificiales, sin cuerda.'),
('Tai Chi', 'Práctica de Tai Chi en parques, enfocada en movimientos lentos y controlados.');

