INSERT INTO sports (name, description) VALUES
('Badminton', 'Racket sport played with a shuttlecock, suitable for parks and beaches.'),
('Basketball', 'Team sport played on open urban courts with a hoop and ball.'),
('Beach Handball', 'Dynamic team sport played on sand, aiming to score by throwing a ball into the opposing team’s goal.'),
('Beach Petanque', 'Variant of petanque played on sand, involving the precision throwing of metal balls.'),
('Beach Soccer', 'Soccer game played on the sand, typically on the beach.'),
('Beach Tennis', 'Tennis played on sand with a portable net, common on beaches.'),
('Beach Volleyball', 'Volleyball played on sand, a popular beach activity.'),
('Bodyweight Training', 'Strength training exercises using only body weight, performed in public spaces.'),
('Capoeira', 'Brazilian martial art combining elements of dance, acrobatics, and music.'),
('Climbing Walls', 'Climbing activities on artificial walls in public spaces, suitable for all skill levels.'),
('Crossfit', 'High-intensity functional group exercises, often conducted in public spaces.'),
('Futsal', 'Indoor soccer played on outdoor concrete or artificial turf courts.'),
('Freestyle Football', 'Performing skills and tricks with a soccer ball in public areas like squares or parks.'),
('Functional Training', 'High-intensity outdoor exercises using one’s own body weight.'),
('Kitesurfing', 'Water sport using a kite to harness the wind and surf on beaches with suitable conditions.'),
('Longboarding', 'Variant of skateboarding, ideal for long distances and downhill rides.'),
('Orienteering Races', 'Navigation races using a map, typically held in urban areas or large parks.'),
('Outdoor Aikido', 'Practicing Aikido movements in open spaces.'),
('Outdoor Boxing', 'Boxing training conducted in parks, using portable equipment.'),
('Paddle Surfing', 'Paddling while standing on a surfboard in calm waters, such as beaches or lakes.'),
('Parkour', 'Moving fluidly and efficiently over urban obstacles.'),
('Petanque', 'Precision game of throwing metal balls, usually played in parks.'),
('Ping Pong', 'Racket sport played with a small ball on a table.'),
('Quad Skating', 'Skating on four-wheeled skates, different from inline skating.'),
('Rollerblading', 'In-line skating in parks, promenades, or wide streets.'),
('Rugby Touch', 'Non-contact version of rugby played on grass or sand.'),
('Running', 'Continuous running on urban routes, parks, or along the coast.'),
('Skateboarding', 'Riding on a skateboard in squares, parks, and skateparks.'),
('Slackline', 'Balancing on a taut belt stretched between two points.'),
('Slackline Acrobatics', 'Advanced form of slacklining with higher and tighter ropes.'),
('Speed Skating', 'Racing or training on inline skates in wide, smooth areas.'),
('Spikeball', 'Competitive game involving a ball and a circular net.'),
('Street Workout', 'Calisthenics exercises performed in parks using bars and street furniture.'),
('Surfing', 'Exciting water sport where individuals ride ocean waves on a surfboard, often performed in coastal areas with suitable wave conditions.'),
('Tai Chi', 'Practice of Tai Chi in parks, focusing on slow and controlled movements.'),
('Ultimate Frisbee', 'Team sport played with a flying disc in parks or beaches.'),
('Urban Cycling', 'Cycling around the city, both as a sport and a means of transportation.'),
('Urban Dance', 'Urban dancing styles like Hip-Hop and Breakdance, performed in public spaces.'),
('Urban Hiking', 'Exploratory walks through the city, parks, and natural areas.'),
('Urban Trekking', 'Long-distance hiking through urban areas and parks.'),
('Volleyball Court', 'Team sport played with a ball and high net.'),
('Yoga', 'Practice of yoga in parks, beaches, or open spaces.');