INSERT INTO sports (name, description) VALUES 
('Badminton', 'Racket game with shuttlecock, can be played in parks and beaches.'),
('Basketball', 'Basketball games on open urban courts'),
('Beach Petanque', 'Variant of petanque played on the sand.'),
('Beach Soccer', 'Soccer game on the sand on the beach.'),
('Beach Tennis', 'Playing tennis on the sand with a portable net.'),
('Beach Volleyball', 'Volleyball played on sand, common on beaches.'),
('Bodyweight Training', 'Strength training using only body weight in public spaces.'),
('Capoeira', 'Brazilian martial art, a mixture of wrestling, dance, and acrobatics.'),
('Crossfit', 'Functional group exercises, using public spaces.'),
('Futsal', 'Soccer on outdoor concrete or artificial turf courts.'),
('Freestyle Football', 'Skills and tricks with the ball in squares or parks.'),
('Functional Training', "High-intensity outdoor exercises using one's own body weight."),
('Grass Volleyball', 'Variant played in parks, on natural grass.'),
('Kitesurfing', 'Using the wind to surf with a kite on beaches with suitable conditions.'),
('Longboarding', 'Variant of skateboarding, ideal for descents and long distances.'),
('Orienteering Races', 'Map navigation in urban areas or large parks.'),
('Outdoor Aikido', 'Practicing Aikido movements in an open space.'),
('Outdoor Boxing', 'Boxing training in parks, using portable equipment.'),
('Paddle Surfing', 'Paddling standing up on a surfboard in calm water (beaches or lakes).'),
('Parkour', 'Moving over urban obstacles in a fluid and efficient manner.'),
('Petanque', 'Precision game of throwing metal balls in parks.'),
('Ping Pong', 'Racket sport with a small ball.'),
('Portable Ping Pong', 'Folding tables or portable nets in squares or parks.'),
('Quad Skating', 'Skating on square wheels, different from inline skating.'),
('Rollerblading', 'In-line skating in parks, promenades, or wide streets.'),
('Rugby Touch', 'Non-contact rugby played on grass or sand.'),
('Running', 'Continuous running on urban routes, parks, or along the coast.'),
('Skateboarding', 'Gliding on boards in squares, parks, and skateparks.'),
('Slackline', 'Balancing on a taut belt between two points.'),
('Slackline Acrobatics', 'Variant of slackline but with higher and tighter ropes.'),
('Speed Skating', 'Racing or training on inline skates on wide, smooth areas.'),
('Spikeball', 'Competitive game with ball and circular net.'),
('Street Workout', 'Calisthenics exercises in parks using bars and street furniture.'),
('Tai Chi', 'Tai Chi practice in parks, focusing on slow and controlled movements.'),
('Ultimate Frisbee', 'Team game with a flying disc in parks or beaches.'),
('Urban Climbing (Buildering)', 'Climbing urban structures (practiced by experts).'),
('Urban Cycling', 'Moving around the city on a bicycle, both as a sport and as a means of transportation.'),
('Urban Dance', 'Urban dancing in squares or parks (Hip-Hop, Breakdance, etc.).'),
('Urban Hiking', 'Exploratory walks through the city, parks, and natural areas.'),
('Urban Trekking', 'Hiking on long routes through urban areas and parks.'),
('Volleyball', 'Team game with ball and high net.'),
('Yoga', 'Yoga practice in parks, beaches, or open spaces.');
